### ISSUE TITLE
Moving the card during the key writing phase can leave the card in a undesirable state

### ISSUE THREAD

**Issue by robertclarkson** [boltcard/bolt-nfc-android-app#10]
During changing the keys, if the card is moved away from the reader before all keys have been changed then the card can be left in a state where some keys are changed and others arent. This is undesirable and also can't currently be recovered with the app.

The app should follow the progress of each key change and if the card is moved too quick the next tap should continue on from where the last tap failed

**Comment by PeterRounce** [comment]
👍

**Comment by robertclarkson** [comment]
This has been mitigated by removing debug output slowing the card changing process and improving the UI to read more along the lines of "hold card to reader until writing has completed"
