### ISSUE TITLE
Query Parameters cause error when writing NFC

### ISSUE THREAD

**Issue by cj-ibex** [boltcard/bolt-nfc-android-app#13]
Error occurs if the url has query parameters, since the `p` and `c` fields have a `?` in front of them, resulting in double `?`s

Is this expected? Is query parameters not supported for now?

Thanks!

**Comment by robertclarkson** [comment]
Query parameters now supported as of v0.0.4
https://github.com/boltcard/bolt-nfc-android-app/commit/a3f8e8cc0170165e3de7c41813ca932c39f1aa96
