### ISSUE TITLE
Suggestions to improve the user experience of the mobile app

### ISSUE THREAD

**Issue by blackcoffeexbt** [boltcard/bolt-nfc-android-app#14]
I've used the mobile app to create some bolt cards and have a few suggestions to tweak the UX a little to make it easier to use:

+ The UID displayed should be lower case as is in the postgres database
+ Can the UID be copied to the mobile device's clipboard to allow it to be shared reducing potential errors? A QR code export of the UID would be really nice
+ Make the URL input field default to a "URL" type so that the first letter isn't uppercased by default.

**Comment by robertclarkson** [comment]
these changes are done in v0.0.5
https://github.com/boltcard/bolt-nfc-android-app/releases/tag/v0.0.5
