### ISSUE TITLE
Order of tabbed navigation

### ISSUE THREAD

**Issue by blackcoffeexbt** [boltcard/bolt-nfc-android-app#17]
As the UX flow (by tab) is as follows

1. Write NFC
1. Read NFC
1. Key management

Would it make sense to switch the Write NFC and Read NFC icons in the bottom nav bar so that the user taps the tabs in a left to right order?

**Comment by robertclarkson** [comment]
Possibly, but the idea is that the tag would be checked first on the read screen so the user can see;
A) if its a compatible tag (NTAG424)
B) if it is able to be read (the keys are set to default)

At this point they can then go to the write sceen knowing that its possible to write the card.

I will admit it's not clear from the docs or screens that this is the idea

**Comment by robertclarkson** [comment]
Stale
