### ISSUE TITLE
Don´t expand lnurw input field out of bounds

### ISSUE THREAD

**Issue by titusz** [boltcard/bolt-nfc-android-app#18]
User cannot verify complete input string without rotating the phone.

![image](https://user-images.githubusercontent.com/278556/185804575-6aa80d37-7d32-4f11-8c41-0a7f346f46ba.png)

**Comment by robertclarkson** [comment]
Fixed in v0.0.7
https://github.com/boltcard/bolt-nfc-android-app/releases/tag/v0.0.7
