### ISSUE TITLE
improve 'wipe card' function user flow

### ISSUE THREAD

**Issue by PeterRounce** [boltcard/bolt-nfc-android-app#24]
There are reports of users bricking cards (telegram group t.me/bolt_card ) which may be improved or made safer with some attention and further testing of the advanced 'wipe card' function and related errors for incorrect key entry, as well as safety of the function when card communication is lost.

Also [documented user flow](https://gist.github.com/iWarpBTC/b88d9aed6ce29d227d68410dada4cd7b) looks sub-optimal

**Comment by iWarpBTC** [comment]
Yea, it would be really nice to be able to disable SDM/SUN mirroring within the app.

**Comment by PeterRounce** [comment]
[video showing the current user flow](https://www.youtube.com/watch?v=Pe0YXHawHvQ)

**Comment by robertclarkson** [comment]
I will allow scanning in of the keys for reset via QR code. We don't need to be precious about security as we're removing these keys. The format should be;

```
{
"k0":"000000000000000000000000000000",
"k1":"000000000000000000000000000000",
"k2":"000000000000000000000000000000",
"k3":"000000000000000000000000000000",
"k4":"000000000000000000000000000000",
"action":"wipe",
"v":1
}
```

Do you think important to have a version?

**Comment by PeterRounce** [comment]
I suggest that the server side mark the card record as **enable=N** at minimum and ideally mark it as **to_be_wiped=Y** before the wipe QR code is shown.

This will help with further card management functions.

I think a version is useful to easily detect any protocol update without having to change the action name.

**Comment by robertclarkson** [comment]
I've set up test mockend QR codes and URLs here: https://github.com/robertclarkson/mockend

**Comment by robertclarkson** [comment]
Ah ive messed this QR code up, should be the keys in teh QR code not a URL. will redo.

**Comment by robertclarkson** [comment]
![image](https://user-images.githubusercontent.com/3826238/202315216-0ae53613-bede-459b-a6bc-e9d06884341c.png)

**Comment by robertclarkson** [comment]
Had a thought it could be good to get the card UID in there as well and then i can check its the correct card beforehand

**Comment by robertclarkson** [comment]
![image](https://user-images.githubusercontent.com/3826238/202380904-ef8f53cf-7111-48ae-9293-138485800e4e.png)

**Comment by robertclarkson** [comment]
New release APK with reset key UX to test
https://github.com/boltcard/bolt-nfc-android-app/releases/tag/v0.1.2

**Comment by iWarpBTC** [comment]
When I succeed to read QR it works pretty well for me. Was surprised that even the counter is being reset. :D 

But I was struggling to read the QR (even the link for new_bolt_card_response), although my phone (OnePlus 6 with Lineage OS 19.1) can read them instantly with random QR reader app. For some reason it helps if I'm bringing the phone closer and further repeatedly. I'm wondering it is only me... 

Also noticed, that the version number in the Help bookmark didn't change (but the commit hash did).

**Comment by robertclarkson** [comment]
Version number, well spotted!

I didnt have any problem scanning the QR code, but if you're on a late model and did, not ideal. I wonder if I accept a URL to parse as well?

There is the option to paste the key JSON in, i feel this could be the way a lot of people do it, esp if they are managing LNBits from their phone. What do you think?

**Comment by iWarpBTC** [comment]
It must have somethink to do with my desktop display! I could even trigger some errors with valid QRs :D But it's signifigantly better with my laptop. Although, I still can't figure out why the experience isn't the same with a generic QR reader app. Never mind, probably just my issue. :) 

Tried also the copy&paste flow and that also works fine.
