### ISSUE TITLE
add enhanced privacy

### ISSUE THREAD

**Issue by PeterRounce** [boltcard/bolt-nfc-android-app#25]
related issue https://github.com/boltcard/boltcard/issues/21

With app v0.1.2 (bd0f5ec) it is possible to write and wipe cards from the [bolt card service that includes the uid_privacy flag](https://github.com/boltcard/boltcard/commit/bc5842374ad5057a5f4d58868991b62ac083373f) because it is ignored by the app.

The bolt card app enhancements should be implemented without affecting the LNbits bolt_card extension until that is ready to adopt the enhanced privacy updates.

The app should detect `create_bolt_card_response v2` when it has `uid_privacy` set to `Y`
It should then authenticate with the card and set `PICCConfig.UseRID=1`
The UID will be random or zero after a card power cycle

In my testing, I've noticed this message when UseRID is set and the create card tests are run.
![screenshot](https://user-images.githubusercontent.com/99006127/205255643-62a634e8-ef58-4a51-ab3b-cf9fbd2a2369.png)

Also the Card UID shown is random and it is easily detectable as the value is shorter than the previous static value.
Perhaps we should show `Card UID: private` instead

**Comment by PeterRounce** [comment]
The TapLinx method to activate the 'random UID' feature is:

https://www.mifare.net/developer/javadoc/android/
Interface INTAG424DNA
void setPICCConfiguration(boolean enableRandomUID)

**Comment by robertclarkson** [comment]
added this feature to test branch https://github.com/boltcard/bolt-nfc-android-app/tree/random-uid

**Comment by PeterRounce** [comment]
all works except.. issue https://github.com/boltcard/bolt-nfc-android-app/issues/29
