### ISSUE TITLE
unexpected error message on programming a wiped card with UID privacy

### ISSUE THREAD

**Issue by PeterRounce** [boltcard/bolt-nfc-android-app#29]
related issue #25 

Steps to reproduce:

- Create a card with the -uid_privacy flag set
- Wipe the card
- Create the same card with the -uid_privacy flag set
- The app indicates an error on the 'Test PICC' stage but the card works fine.

![205255643-62a634e8-ef58-4a51-ab3b-cf9fbd2a2369](https://user-images.githubusercontent.com/99006127/216040160-67039b10-0827-41f3-aeb1-a1f72726bbee.png)

I think this is due to the UID being decrypted not being the same as the UID read from the card.
This is to be expected and can show as ok (green tick).

**Comment by PeterRounce** [comment]
I think branch [random-uid](https://github.com/boltcard/bolt-nfc-android-app/tree/random-uid) can be merged to main for a new release once this is fixed

I've tested (and fixed) the server side
( issue https://github.com/boltcard/boltcard/issues/26 )

**Comment by robertclarkson** [comment]
Done
