### ISSUE TITLE
Fix for boltcard bricking caused by false version assumptions

### ISSUE THREAD

**Issue by johnheenan** [boltcard/bolt-nfc-android-app#44]
Please see Pull Request at https://github.com/boltcard/bolt-nfc-android-app/pull/43 for a fix for boltcards becoming bricking after a reset using BTCPay Server.

It is clear from the code changes that the assumption a reset version number is always 0 and a setup version number is always 1 is unnecessary.

These changes have been tested with boltcards issued by BTCPay Server. A card that has been reset through BTCPay Server can now be sucessfully setup again. Previously the boltcard was bricked from using again after a reset.
 
An improvement to this fix might be that if no version is provided from a json resposne then a default can be assumed of 1 for setup and 0 for reset, instead of throwing an error.

**Comment by johnheenan** [comment]
I have added a second commit to the Pull Request to assing default versions if not provided.

**Comment by NicolasDorier** [comment]
@johnheenan can you tell me the step by step process to brick a card prior to this fix?

**Comment by NicolasDorier** [comment]
So if I understand, before this fix:
1. A setup would assume ChangeKey v0
2. A reset would set ChangeKey v1
3. A new setup would assume the wrong version => Crash!

But if that was the case, it should not be possible to Setup and Reset and Setup again with the Boltcard Creator, but I never had issue with it.

**Comment by johnheenan** [comment]
> So if I understand, before this fix:
> 
> 1. A setup would assume ChangeKey v0

BTCPay Server passes key value 1, the app assumes value 1 without checking. Eceryone is happy

> 2. A reset would set ChangeKey v1

BTCPay Server passes key value 2, the app assumes value 0 without checking. Card appears OK but is bricked as setup will not work again.

> 3. A new setup would assume the wrong version => Crash!

Correct.

> But if that was the case, it should not be possible to Setup and Reset and Setup again with the Boltcard Creator, but I never had issue with it.

You are missing a step. Try setup, reset THEN setup again. Won't work before fix. Works after fix

> On top of it, reading the ntag documentation, the version of a key doesn't have any meaning. You can pass whatever you want there and retrieve with `GetKeyVersion` that's it.

Exactly. We impose our own meaning.

**Comment by NicolasDorier** [comment]
I tried you steps.

* Created a factory in BTCPay
* Scan QR with phone
* Click on Setup on the browser
* Program the card with boltcard app
* Back to browser
* Click on Reset
* Reset the card with boltcard app
* **Close the boltcard app** <- This seems to be needed, else there is an error for some reason
* Back to browser
* Click on Program
* Program the card again

This worked fine

**Comment by johnheenan** [comment]
I don't scan a QR and I have not had to close the boltcard app. When I place the boltcard to the phone with BTCPay open in the browser, the phone automatically navigates to the right screen on the boltcard app. When finished, I then navigate back to BTCPay on the browser with the mobile phone tab key. I don't close the botcard app.

I will post the console logs from the boltcard app showing how the version value passed by BTCPay increments. If necessary I will post a video of the entire process on the phone. The boltcard app ignores the version number passed.

> If we impose our own meaning, why would setting the wrong version in ChangeKey cause any kind of issue?

First, no specifc version key is programmed into the bolt card. It is only used to caculate programmed key values. Second, BTCPay Server must retain an arbitrary key value because BTCPAy Server does not retain keys, it calculates keys as needed. So it is an issue to ensure key values  match. Other than that, we impose our own meaning. The key value is only allowed to be one byte long, so it can only go from value 0 to value 255.

**Comment by NicolasDorier** [comment]
I am not sure what we are doing differently really. I don't have any issue.
I need to close the boltcard app, and it just work, no card bricked. It would be helpful if you can make a video of it, I really fail to replicate the bricking.

>  The boltcard app ignores the version number passed.

Yes, and I don't understand why it would cause anything to crash. I don't understand why having the version number saved into the boltcard would somehow fix anything by itself.

**Comment by johnheenan** [comment]
OK video in next few hours. I cannot prepare one now.

Just a slight clarification. What the boltcard app receives are five intermediate keys. The final keys stored use the key value as part of the calculation of final stored keys.

**Comment by robertclarkson** [comment]
In the spec the key versions are for any purpose the developer deems neccessary and so I decided when a card is set up with keys it is set it to 1 and then when the card is reset we set the key version back to 0. 

This could be handy for someone to know what state the card keys are in, but I am not sure what John want's to do with the versioning.

I am not sure why key versioning would have any effect on bricking a card

**Comment by NicolasDorier** [comment]
> What the boltcard app receives are five intermediate keys. The final keys stored use the version value as part of the calculation of final stored keys.

So you mean that `Intermerdiate keys` +`Version` = `Final Key Stored` ?
I am don't think it is the case, else call to Authenticate would require to know the version. But the version isn't used at all. 

`AuthenticateEV2First/AuthenticateEV2NonFirst` don't need the version.

**Comment by johnheenan** [comment]
> So you mean that `Intermerdiate keys` +`Version` = `Final Key Stored` ?

Yes but not that simply. The 'intermediate keys' are arbitrary made up values. The final keys are not.

> I am don't think it is the case, else call to Authenticate would require to know the version. But the version isn't used at all.

Correct, authenticate does not need to know the value. But BTCPay server needs to know the version because BTCPay needs to recalculate the keys on the fly and they cannot be recaculated without the version value. 

If BTCPay server did store keys (instead of regenearating when needed) then the version value is not required.

**Comment by johnheenan** [comment]
With regard to creating to a video to reproduce the problem there are anomalies.

The current re downloaded version of boltard creator app on the Play Store is behaving differently to the one I downloaded some months ago. There was no indication of an upgrade.

The version compiled from the current source code is not behaving the same way as the current app in the store but is behaving the same way as the app I downloaded from the store before. The v0.3.1 latest app on github is dated Janaury 26 (seven months ago) and the version in the Play Store is dated January 25.

With the version compiled from current unmodified source, my boltcards brick. With the current version from the Play Store, my boltcards do not brick.

This is just so weird. I will try and sort this out as best I can at my end and provide further information, backedc up by logs and references to source code, if applicable.

**Comment by johnheenan** [comment]
From the NTAG manual:

> **8.2.4.6 Key version**

> A 1-byte key version (00h to FFh) is assigned to each key. This key version can be used
> to distinguish the keys of a specific application if the same application uses different keys
> or key versions.

> The key version is set with the ChangeKey command and can be retrieved using the
> GetVersion command.

I don't find this very helpful or clear. It does not even look accurate, according to definitions elsewhere in the NTAG manual.

When clarity is required look at reference code that works for confirmation. The GetVersion in implementations returns unchangeable information about hardware, software and production.

From my examination of source code and the NTAG manual, it is clear the Key version value is used as part of  a complex calculation to store a final key value. It is also clear that none of the five keys need have the same version value.

**Comment by NicolasDorier** [comment]
BTCPay use version internally because if we didn't rotate keys after every setup/reset cycles, then we would end up reusing the same keys with already used counter.

The version of the spec I wrote on deeplink isn't related to the version keys on the boltcards. While it would be possible to store the version on the boltcards, it shouldn't influence anything on the boltcard. The version passed can be any value, and it should still work.

1. It doesn't make sense to me that your fix should change anything
2. What is the version on android store? If the master is bricking cards, a bug may have sneaked in and I can quickly compare with the android store version.

**Comment by johnheenan** [comment]
> It doesn't make sense to me that your fix should change anything

It does if you expect different key Version values BTCPay passes through to be respected. They are ignored in current boltcard creator source code.

> What is the version on android store? 

As mentioned above, v0.3.1 from 25 January

> If the master is bricking cards, a bug may have sneaked in and I can quickly compare with the android store version.

It could be a simple reversion in the current master that was not in the Android version used to build for the App Store. You may not even have access to the real source code used.

There are various reasons not to use the reported master as the real source when compiling code. I do it myself to avoid confusion and polluting Pull Requests, such as with inevitable changes and updates in configuration files.

There is very good reason to believe the master is a hodge podge collection copy of files from various sources.  The source code files have widely varying formats. Just run the prettier code formatter using the provided .prettierrc.js file and the source code files change dramatically. To me this seems convincing the master is not the real source, probably for good reasons.

**Comment by robertclarkson** [comment]
> From my examination of source code and the NTAG manual, it is clear the Key version value is used as part of a complex calculation to store a final key value. It is also clear that none of the five keys need have the same version value.

Can you please provide evidence the key version is used to calculate the final key value

**Comment by johnheenan** [comment]
> Can you please provide evidence the key version is used to calculate the final key value

Three images below from 

1. NTAG manual
2. Your own specs (partially used by BTCPay Server)
3. Your own code implementation for the boltcard creator app.

I should also have a look at what your own boltcard service server does.

To be honest, the implentation looks badly confused. It looks boltcard service BTCPay Server is applying one key version, the boltcard creator app is applying a possibly different key version UNNECESSARILY A SECOND TIME and it is getting accepted somehow by BTCPay Server for real world use!

From the NTAG manual (outlined in yellow):
![ntag manual ChangeKet Table 63](https://github.com/user-attachments/assets/2d997221-9574-4e4a-bc00-cc2ac9b0ae47)

From your own https://github.com/boltcard/boltcard/blob/main/docs/DETERMINISTIC.md
(outlined in yellow), partially used by BTCPay Server. The PRF is specfied further down. 
![deterministic](https://github.com/user-attachments/assets/62cb9578-33ec-4e9a-836f-9197ff80192c)

From this repositories for the boltcard creator app https://github.com/boltcard/bolt-nfc-android-app/blob/master/src/class/Ntag424.js
with blue dots around KeyVersion (four occurrences):
![Ntag424 js](https://github.com/user-attachments/assets/2f0c2ae6-a03b-4aed-ac44-da83f3645481)

**Comment by NicolasDorier** [comment]
As I said, the Key Version on the spec isn't related to the KeyVer from NTag. It doesn't have to be related.

As for the code you are showing, it is about calling `ChangeKey`, keyVersion can be ANY number from 0 to 255, and it will always work, it doesn't matter if there is a mismatch.

**Comment by johnheenan** [comment]
> As I said, the Key Version on the spec isn't related to the KeyVer from NTag. It doesn't have to be related.

I accept you can do double encoding with unrelated key versions at different layers. Such practices are common.

But it does not alter the fact that at some layer BTCPay is passing a key version value and it is being ignored. It is pretty much black and white, as indicated at https://github.com/boltcard/bolt-nfc-android-app/pull/43#issuecomment-2316361784

**Comment by NicolasDorier** [comment]
> When I don't ignore the version number provided in my fix, my cards don't become bricked.

I just want to be able to reproduce it to check if that is the actual problem, but I don't manage to...

**Comment by johnheenan** [comment]
I have looked through source code in detail and confirm that:

1. There are two types of key versions
2.  They are not related
3.  They are not layered in the usual meaning
4. One is solely to manage issuance of five NTAG customer defined keys and it has nothing to do how keys are encoded in an NTAG
5. The other key type is an additional arbitrary one byte value that can be independently saved with each key, can be independently retrieved from each key and has no effect on card key functionality.
6. The version from key issuance is sent to the boltcard creator app but it does not need to use it for anything. If it wanted it could record a version less than 256 with one to five keys does not need to. 

So now I still do not know why I am getting very high levels of card bricking.

Thanks to @NicolasDorier and @robertclarkson for putting up with me and their fantastic work.
